const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "258858286090"
const SESSION_ID = "PRABATH-MD~PV0CUSxb#e_aAE4YZk5Ie2ENTDRA6lhk8ypAQVCjL_Cyre4Y1cXc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
